### ISSUE TITLE
[RESOLVED] Default Hosts

### ISSUE THREAD

**Issue by gitdine** [bongochong/CWP-Utilities#2]
Firstly, thanks for this neat tool. it works flawlessly and saves a lot of time.

The Malware domains list is seemingly no longer maintained and now just [points to an empty file](https://www.malwaredomainlist.com/hostslist/hosts.txt), it should probably be removed from the default list of hosts files.

Here are some active malware lists you could used instead:
https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt
https://curben.gitlab.io/malware-filter/urlhaus-filter-hosts-online.txt
https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts

**Comment by bongochong** [comment]
Thanks for the positive and useful feedback! Fortunately, the most recent version of CWP-Utilities includes a script update function, which you can find in the console and system tray interfaces (in the latter, it is under the 'help' sub-menu). If you haven't upgraded to version 1.7.8, here's the release page: https://github.com/bongochong/CWP-Utilities/releases/tag/1.7.8  

For good measure, do run the aforementioned update function after installation, and new default lists will be fetched (straight from this GitHub repo). I regularly check to make sure that the default lists and core functionality in CWP-Utilities is roughly equivalent to the utilities in my GNU/Linux repo, which is why I included the script update function in the most recent release.  

I've been putting a good amount of effort and thought into the next release (which should be arriving by the end of January 2021), so I can hopefully expand the built-in update functionality to make it even easier for users to keep in sync with changes to the main scripts. After that, I hope to set aside enough time for working on a more capable and unified interface.  

Cheers! 🍻
